community/zig: use alpine-linux rust targets
Our rust targets are called alpine-linux and therefore would fail:

	error[E0463]: can't find crate for `core`
	  |
	  = note: the `x86_64-unknown-linux-musl` target may not be installed
	  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`