gthumb: remove gstreamer subpackage, enable by default
currently, gthumb-gstreamer cannot be installed, since it both depends
on the main gthumb package, as well conflicts with it:

	❯ doas apk add gthumb-gstreamer
	fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
	fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
	fetch https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz

	ERROR: unable to select packages:
	  gthumb-3.12.7-r0:
	    conflicts: gthumb-gstreamer-3.12.7-r0[so:gthumb:libslideshow.so=0]
		       gthumb-gstreamer-3.12.7-r0[cmd:gthumb=3.12.7-r0]
	    satisfies: world[gthumb] gthumb-gstreamer-3.12.7-r0[gthumb=3.12.7-r0]
	  gthumb-gstreamer-3.12.7-r0:
	    conflicts: gthumb-3.12.7-r0[so:gthumb:libslideshow.so=0] gthumb-3.12.7-r0[cmd:gthumb=3.12.7-r0]
	    satisfies: world[gthumb-gstreamer]

This commit just enables gstreamer in the main package. It increases the
size by about 220KiB:

	gthumb-3.12.7-r0 installed size:
	4738 KiB

	gthumb-3.12.7-r1 installed size:
	4961 KiB